<a href="https://colab.research.google.com/github/IraAndreykiv/ML/blob/main/Lab2_ML(Andreykiv).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import random
import numpy as np
import time

In [ ]:
matrix1 = [[random.randint(0, 1) for _ in range(100)] for _ in range(100)]
matrix2 = [[random.randint(0, 1) for _ in range(100)] for _ in range(100)]
matrix = [[random.randint(0, 1) for _ in range(100)] for _ in range(100)]
vector1 = [random.randint(0, 1) for _ in range(100)]
vector2 = [random.randint(0, 1) for _ in range(100)]
vector = [random.randint(0, 1) for _ in range(100)]

In [ ]:
def MatrixByMatrix(matrix1, matrix2):
  return [[sum(matrix1[i][k] * matrix2[k][j]
   for i in range(len(matrix1)))
     for j in range(len(matrix2))]
         for k in range(len(matrix2[0]))]

In [ ]:
matrix1 = np.array( [[random.randint(0, 1) for _ in range(100)] for _ in range(100)] )
matrix2 = np.array( [[random.randint(0, 1) for _ in range(100)] for _ in range(100)] )
matrix1 @ matrix2

array([[30, 28, 27, ..., 24, 33, 29],
       [24, 18, 22, ..., 16, 22, 21],
       [26, 26, 28, ..., 19, 29, 28],
       ...,
       [26, 21, 29, ..., 23, 22, 29],
       [21, 24, 26, ..., 18, 23, 24],
       [27, 28, 30, ..., 26, 28, 30]])

In [ ]:
start_time = time.time()
MatrixByMatrix(matrix1, matrix2)
print("%s seconds" % (time.time() - start_time))

0.6673345565795898 seconds


In [ ]:
start_time = time.time()
matrix1 = np.array( [[random.randint(0, 1) for _ in range(100)] for _ in range(100)] )
matrix2 = np.array( [[random.randint(0, 1) for _ in range(100)] for _ in range(100)] )
matrix1 @ matrix2
print("%s seconds" % (time.time() - start_time))

0.03977775573730469 seconds


In [ ]:
def MatrixByVector(matrix1, vector):
    result = []
    for i in range(len(matrix1[0])): 
        total = 0
        for j in range(len(vector)): 
            total +=  matrix1[j][i] * vector[j]
        result.append(total)
    return result

In [ ]:
matrix1 = np.array( [[random.randint(0, 1) for _ in range(100)] for _ in range(100)] )
vector = np.array([random.randint(0, 1) for _ in range(100)])
matrix1 @ vector

array([21, 33, 31, 27, 29, 19, 26, 21, 29, 26, 26, 25, 26, 24, 24, 26, 27,
       30, 26, 24, 25, 24, 27, 25, 18, 24, 27, 28, 32, 33, 29, 27, 28, 24,
       24, 25, 25, 28, 20, 23, 24, 24, 27, 28, 25, 29, 25, 25, 33, 30, 22,
       29, 31, 25, 27, 22, 20, 27, 24, 36, 31, 30, 22, 25, 28, 23, 24, 22,
       26, 26, 28, 25, 27, 30, 30, 27, 22, 36, 30, 28, 25, 28, 33, 28, 30,
       29, 30, 29, 25, 30, 30, 34, 25, 31, 26, 29, 23, 23, 22, 29])

In [ ]:
start_time = time.time()
MatrixByVector(matrix1, vector)
print("%s seconds" % (time.time() - start_time))

0.008498907089233398 seconds


In [ ]:
start_time = time.time()
matrix1 = np.array( [[random.randint(0, 1) for _ in range(100)] for _ in range(100)] )
vector = np.array([random.randint(0, 1) for _ in range(100)])
matrix1 @ vector
print("%s seconds" % (time.time() - start_time))

0.014772653579711914 seconds


In [ ]:
def VectorByMatrix(vector, matrix):
    result = [0 for i in range(len(vector))]
    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            result[i] += matrix[j][i] * vector[j]
    return result

In [ ]:
matrix = np.array([[random.randint(0, 1) for _ in range(100)] for _ in range(100)])
vector = np.array([random.randint(0, 1) for _ in range(100)])
vector @ matrix

array([25, 25, 23, 17, 19, 25, 25, 19, 21, 29, 18, 27, 26, 23, 19, 15, 27,
       30, 24, 28, 25, 25, 30, 24, 26, 31, 25, 25, 18, 22, 29, 24, 23, 20,
       22, 24, 27, 19, 23, 27, 18, 24, 31, 22, 21, 23, 20, 26, 23, 22, 18,
       20, 22, 26, 25, 29, 26, 23, 20, 28, 28, 23, 30, 20, 26, 22, 26, 18,
       23, 24, 27, 17, 26, 25, 31, 28, 31, 20, 19, 27, 25, 25, 21, 22, 24,
       21, 24, 30, 23, 25, 29, 25, 24, 29, 20, 28, 22, 23, 24, 21])

In [ ]:
start_time = time.time()
VectorByMatrix(vector, matrix)
print("%s seconds" % (time.time() - start_time))

0.008708000183105469 seconds


In [ ]:
start_time = time.time()
matrix = np.array([[random.randint(0, 1) for _ in range(100)] for _ in range(100)])
vector = np.array([random.randint(0, 1) for _ in range(100)])
vector @ matrix
print("%s seconds" % (time.time() - start_time))

0.018584489822387695 seconds


In [ ]:
def VectorByVector(vector1, vector2):
  total = [0]
  for i in range(len(vector1)):
    for j in range(len(vector2)):
      total = sum(vector1 * vector2)
      return total

In [ ]:
vector1 = np.array([random.randint(0, 1) for _ in range(100)])
vector2 = np.array([random.randint(0, 1) for _ in range(100)])
vector1 @ vector2

22

In [ ]:
start_time = time.time()
VectorByVector(vector1, vector2)
print("%s seconds" % (time.time() - start_time))

0.00017976760864257812 seconds


In [ ]:
start_time = time.time()
vector1 = np.array([random.randint(0, 1) for _ in range(100)])
vector2 = np.array([random.randint(0, 1) for _ in range(100)])
vector1 @ vector2
print("%s seconds" % (time.time() - start_time))

0.002177715301513672 seconds


In [ ]:
import random
import unittest

In [ ]:
class Test(unittest.TestCase):
    def test_multiply_Matrix_By_Matrix(self):
        matrix1 = [[random.randint(0, 1) for _ in range(100)] for _ in range(100)]
        matrix2 = [[random.randint(0, 1) for _ in range(100)] for _ in range(100)]
        self.assertEqual(MatrixByMatrix(matrix1, matrix2), matrix1 @ matrix2(matrix1, matrix2))

In [ ]:
def test_multiply_Vector_By_Matrix(self):
        matrix = [[random.randint(0, 1) for _ in range(100)] for _ in range(100)]
        vector = [random.randint(0, 1) for _ in range(100)]
        self.assertEqual(VectorByMatrix(matrix, vector), vector @ matrix(matrix, vector))

In [ ]:
def test_multiply_Vector_By_Matrix(self):
        vec = [random.randint(0, 1) for _ in range(100)]
        mat = [[random.randint(0, 1) for _ in range(100)] for _ in range(100)]
        self.assertEqual(VectorByMatrix(vector, matrix), vector @ matrix (vector, matrix))

In [ ]:
def test_multiply_Vector_By_Vector(self):
        vec1 = [random.randint(0, 1) for _ in range(100)]
        vec2 = [random.randint(0, 1) for _ in range(100)]
        self.assertEqual(VectorByVector(vector1, vector2), vector1 @ vector2(vec1, vec2))